# Generated by Django 5.2.16 on 2026-08-02 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='category',
            field=models.CharField(choices=[('process', 'Process Photo'), ('results', 'Data / Results')], default='process', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
