# Generated by Django 5.2.16 on 2026-08-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectimage_category_alter_projectimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=600),
        ),
    ]
