# Generated by Django 5.2.16 on 2026-08-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projectimage_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimage',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='project_gallery/videos/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_gallery/'),
        ),
    ]
