# Generated by Django 5.2.16 on 2026-08-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_projectimage_video_alter_projectimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('date', models.DateField()),
                ('tags', models.ManyToManyField(blank=True, related_name='news_items', to='projects.tag')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
