# Generated by Django 5.2.16 on 2026-08-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_newsitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
    ]
