# Generated by Django 5.2.16 on 2026-08-10 21:22

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_newsitem_description_newsitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='video',
            field=models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='project_gallery/videos/'),
        ),
    ]
