# These are ADDITIONS/CHANGES to make in your research_site/settings.py
# (the file auto-generated by `django-admin startproject`).
# Don't replace the whole file — just add/edit these specific parts.

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "projects",  # <-- add this line so Django knows the app exists
]

# ---- Static files (CSS) ----
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]

# ---- Media files (uploaded images) ----
# MEDIA_URL is the URL prefix for uploaded files (what browsers request)
# MEDIA_ROOT is the actual folder on disk where they get saved
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
